# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contact.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'contact.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontact.proto\x12\x07\x63ontact\"\"\n\x12\x43ontactNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\":\n\x07\x43ontact\x12\x12\n\nelement_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\"9\n\x13\x43ontactListResponse\x12\"\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x10.contact.Contact2`\n\x0e\x43ontactService\x12N\n\x11GetContactsByName\x12\x1b.contact.ContactNameRequest\x1a\x1c.contact.ContactListResponseB%\n\x13\x63om.example.contactB\x0c\x43ontactProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.example.contactB\014ContactProtoP\001'
  _globals['_CONTACTNAMEREQUEST']._serialized_start=26
  _globals['_CONTACTNAMEREQUEST']._serialized_end=60
  _globals['_CONTACT']._serialized_start=62
  _globals['_CONTACT']._serialized_end=120
  _globals['_CONTACTLISTRESPONSE']._serialized_start=122
  _globals['_CONTACTLISTRESPONSE']._serialized_end=179
  _globals['_CONTACTSERVICE']._serialized_start=181
  _globals['_CONTACTSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
