spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:profiledb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:example}
server.port=${PORT}