spring.application.name=${APP_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}

logging.level.org.hibernate.SQL=${LOGGING_LEVEL_HIBERNATE_SQL}

app.cors.allowed-origin=${CORS_ALLOWED}

spring.data.redis.host=${HOST_REDIS}
spring.data.redis.port=${PORT_REDIS}
spring.data.redis.password=${PASS_REDIS}
