# dev-contact-update.yml
name: 🔧 Dev · Contact Update Service

on:
  push:
    branches: [ "development" ]
    paths:
      - 'Contacts/contact-update-service/**'
      - '.github/workflows/dev-contact-update.yml'

  pull_request:
    branches: [ "QA" ]
    paths:
      - 'Contacts/contact-update-service/**'
      - '.github/workflows/dev-contact-update.yml'
