# dev-contact-read-name.yml
name: 🔧 Dev · Contact Read Name Service

on:
  push:
    branches: [ "development" ]
    paths:
      - 'Contacts/contact-read-name-service/**'
      - '.github/workflows/dev-contact-read-name.yml'

  pull_request:
    branches: [ "QA" ]
    paths:
      - 'Contacts/contact-read-name-service/**'
      - '.github/workflows/dev-contact-read-name.yml'
