# dev-contact-create.yml
name: 🔧 Dev · Contact Create Service

on:
  push:
    branches: [ "development" ]
    paths:
      - 'Contacts/contact-create-service/**'
      - '.github/workflows/dev-contact-create.yml'

  pull_request:
    branches: [ "QA" ]
    paths:
      - 'Contacts/contact-create-service/**'
      - '.github/workflows/dev-contact-create.yml'
