# dev-presence-connect.yml
name: 🔧 Dev · Presence Connect Service

on:
  push:
    branches: [ "development" ]
    paths:
      - 'Connection/presence-connect-service/**'
      - '.github/workflows/dev-presence-connect.yml'

  pull_request:
    branches: [ "QA" ]
    paths:
      - 'Connection/presence-connect-service/**'
      - '.github/workflows/dev-presence-connect.yml'
