# dev-contact-read-phone.yml
name: 🔧 Dev · Contact Read Phone Service

on:
  push:
    branches: [ "development" ]
    paths:
      - 'Contacts/contact-read-phone-service/**'
      - '.github/workflows/dev-contact-read-phone.yml'

  pull_request:
    branches: [ "QA" ]
    paths:
      - 'Contacts/contact-read-phone-service/**'
      - '.github/workflows/dev-contact-read-phone.yml'
