name: CI/CD for Profile Read Service

on:
  push:
    paths:
      - 'Users/profile-read-service/**'
      - '.github/workflows/profile-read.yml'
    branches: [ "development" ]
  pull_request:
    paths:
      - 'Users/profile-read-service/**'
      - '.github/workflows/profile-read.yml'
    branches: [ "QA", "main" ]

jobs:
  deploy:
    name: 🚀 Deploy to EC2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Users/profile-read-service
    steps:
      - name: 📅 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📏 Create temporary .env
        run: |
          echo "DB_USERNAME=${{ secrets.POSTGRES_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.POSTGRES_DB }}" >> .env

      - name: 🏐 Build and push Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/profile-read-service:${{ github.run_number }} \
            --tag ${{ secrets.DOCKER_USERNAME }}/profile-read-service:latest

          rm .env

          docker push ${{ secrets.DOCKER_USERNAME }}/profile-read-service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/profile-read-service:latest

      - name: 🔐 SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_PROFILE_READ }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY2 }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "🚧 Docker no está instalado. Instalando Docker..."
              while sudo fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
                echo "🔒 Esperando que se libere el lock de apt..."
                sleep 5
              done
              sudo rm -f /var/lib/apt/lists/lock
              sudo rm -f /var/lib/dpkg/lock*
              sudo dpkg --configure -a
              sudo apt-get update
              sudo apt-get install -y \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg \
                software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo \
                "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            else
              echo "✅ Docker ya está instalado"
            fi

            echo "🐳 Desplegando contenedor..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/profile-read-service:latest
            sudo docker stop profile-read-service || true
            sudo docker rm profile-read-service || true
            sudo docker run -d --name profile-read-service -p ${{ secrets.PORT_PROFILE_READ }}:3008 \
              -e DB_USERNAME=${{ secrets.POSTGRES_USER }} \
              -e DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e DB_HOST=${{ secrets.POSTGRES_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.POSTGRES_DB }} \
              ${{ secrets.DOCKER_USERNAME }}/profile-read-service:latest
